# Generated by Django 4.2.7 on 2023-11-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=512, null=True)),
                ('type_icon', models.CharField(blank=True, max_length=512, null=True)),
                ('type_name', models.CharField(blank=True, max_length=512, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=512, null=True)),
                ('assignee_avatar', models.CharField(blank=True, max_length=512, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('original_id', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('issue_id', models.CharField(blank=True, max_length=512, null=True)),
                ('estimation', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=32, null=True)),
                ('board', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='main.boards')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enhancement', to='main.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_boarding', models.BooleanField(default=False)),
                ('google_access_token', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=52, null=True)),
                ('htmlLink', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.CharField(blank=True, max_length=32, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=32, null=True)),
                ('end', models.CharField(blank=True, max_length=32, null=True)),
                ('attendees', models.JSONField(blank=True, default=None, null=True)),
                ('organizer', models.JSONField(blank=True, default=None, null=True)),
                ('task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='main.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
