# Generated by Django 4.2.7 on 2023-11-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='tasks',
            field=models.ManyToManyField(related_name='board', to='main.tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='main.events'),
        ),
    ]
