# Generated by Django 4.2.7 on 2023-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_boards_tasks_tasks_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='htmlLink',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='updated',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
