# Generated by Django 4.2.7 on 2023-11-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events_created_events_description_events_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskenhancement',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enhancement', to='main.tasks'),
        ),
        migrations.AddField(
            model_name='taskenhancement',
            name='value',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
