# Generated by Django 4.2.7 on 2023-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_taskenhancement_task_taskenhancement_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskenhancement',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='taskenhancement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='taskenhancement',
            name='name',
        ),
        migrations.AddField(
            model_name='events',
            name='attendees',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='taskenhancement',
            name='value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
