# Generated by Django 4.2.7 on 2023-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_taskenhancement_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
