# Generated by Django 4.2.7 on 2023-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskenhancement',
            name='value',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
