# Generated by Django 4.2.7 on 2023-11-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_taskenhancement_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='main.boards'),
        ),
    ]
