# Generated by Django 4.2.7 on 2023-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_boards_tasks_tasks_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='type_icon',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='type_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
