# Generated by Django 4.2.7 on 2023-11-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_boards_tasks_tasks_board'),
        ('main', '0008_tasks_type_icon_tasks_type_name'),
    ]

    operations = [
    ]
