# Generated by Django 4.2.7 on 2023-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('profile', '0002_profile_jira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jira',
        ),
        migrations.AddField(
            model_name='profile',
            name='available_services',
            field=models.ManyToManyField(related_name='profile', to='main.availableservices'),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_boarding',
            field=models.BooleanField(default=False),
        ),
    ]
